config/routes.rb
Rails.application.routes.draw do
	root 'presentation#home'
	get '/team', to: 'presentation#team'
	get '/contact', to: 'presentation#contact'
	get 'home/:first_name', to: 'presentation#welcome'
	get '/home', to: 'presentation#home'
	get 'gossips/:id', to: 'gossip#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
	def show
		@gossip = Gossip.find(params[:id])
	end
end

app/controllers/presentation_controller.rb
class PresentationController < ApplicationController
	def team
	end

	def contact
	end

	def welcome	
		@gossip = Gossip.all
	end

	def home
		@gossip = Gossip.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/presentation_helper.rb
module PresentationHelper
end

app/views/gossip/show.html.erb
<p>Author :
  <%= @gossip.author %>
</p>
<p>Content :
  <%= @gossip.content %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Gossip</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Home", home_path, class: "nav-item nav-link" %>
        <%= link_to "Team", team_path, class: "nav-item nav-link" %>
        <%= link_to "Contact", contact_path, class: "nav-item nav-link" %>
      </div>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/presentation/contact.html.erb
<div class = 'container_fluid'>
  <h2> Solo Team </h2>
  <p>@Handa</p>
</div>

app/views/presentation/home.html.erb
<h1>Home</h1>
<p>Welcome
  <%= params[:first_name] %>!</p>
<h3>All Gossips :</h3>
<div class="row">
  <% @gossip.each do |gossip| %>
  <div class="card w-25">
    <div class="card-body">
      <h5 class="card-title">
        <%= gossip.author %>
      </h5>
      <p class="card-text">
        <%= gossip.content %>
      </p>
      <a href="/gossips/<%= gossip.id %>" class="btn btn-primary">Read more</a>
    </div>
  </div>
  <% end %>
</div>

app/views/presentation/team.html.erb
<p> You can email us at hello@team.com</p>

app/views/presentation/welcome.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/home">The Gossip</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/team">Team <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact</a>
      </li>        
      <li class="nav-item">
        <a class="nav-link" href="/home">Home</a>
      </li> 
    </ul>
  </div>
</nav>


<h1> Welcome, <%= params[:first_name] %> </h1>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p><% @gossip.each do |gossip| %>
    <%= gossip.author %>
    <%= gossip.content %>
    <%end%>
    <a href="#" class="btn btn-primary">Go somewhere</a>
    </p>
 